### ISSUE TITLE
Compilieren 8266

### ISSUE THREAD

**Issue by mzielinskim** [Yattien/ESPEInk_ESP8266#3]
Benötigte Libs:
PubSubClient
ESP8266httpUpddate

Nach Installation der beiden 
bekomme ich trotzdem einen Fehler
zu ESP8266httpUpddate

**Comment by Yattien** [comment]
- [x] PubSubClient
- [ ] ESP8266httpUpddate

Eine zuästzliche Lib "ESP8266httpUpdate" habe ich nicht installiert. Welchen Fehler bekommst du, wenn du die wieder deinstallierst? Welche Entwicklungsumgebung (Arduino 1.x?) nutzt du?

**Comment by mzielinskim** [comment]
Ich habe die Arduino IDE eben nochmal komplett gelöscht und alle Library-Folder geleert.
 
Dann Installiert:
ArduinoJson
PubSubClient
WiFiManager

beim compilieren kommt:
Arduino: 1.8.15 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

D:\PC\Hardware\raspberry\fhem\epaper\ESPEInk_ESP8266\ESPEInk_ESP8266\ESPEInk_ESP8266.ino: In function 'void getUpdate()':
ESPEInk_ESP8266:218:67: error: no matching function for call to 'ESP8266HTTPUpdate::update(String&)'

  218 |    t_httpUpdate_return ret = ESPhttpUpdate.update(firmwareImageUrl);

In file included from D:\PC\Hardware\raspberry\fhem\epaper\ESPEInk_ESP8266\ESPEInk_ESP8266\ESPEInk_ESP8266.ino

**Comment by Yattien** [comment]
Danke für die Überprüfung, mehr Libs habe ich auch nicht installiert.
Die fehlenden Funktionen sind im Board-Package zum ESP8266 enthalten. Falls du das noch nicht installiert hast:
* Unter _Datei/Voreinstellungen_ die ESP8266-Definitionen hinzufügen "_http://arduino.esp8266.com/stable/package_esp8266com_index.json_"
* Dann unter _Werkzeuge->Board: [...]->Boardverwalter..._ das Package "_esp8266_" suchen und installieren

**Comment by mzielinskim** [comment]
Ich hatte auf Board NodeNCU gestellt (sieht man auch im Protokoll) - beim Umstellen auf Generic8266 kommen die Fehler mit denen alles begann:


Arduino: 1.8.15 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

D:\PC\Hardware\raspberry\fhem\epaper\ESPEInk_ESP8266\ESPEInk_ESP8266\ESPEInk_ESP8266.ino: In function 'void getUpdate()':

ESPEInk_ESP8266:218:67: error: no matching function for call to 'ESP8266HTTPUpdate::update(String&)'

  218 |    t_httpUpdate_return ret = ESPhttpUpdate.update(firmwareImageUrl);

      |                                                                   ^

In file included from D:\PC\Hardware\raspberry\fhem\epaper\ESPEInk_ESP8266\ESPEInk_ESP8266\ESPEInk_ESP8266.ino:19:

C:\Users\Michael Zielinski\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:128:25: note: candidate: 't_httpUpdate_return ESP8266HTTPUpdate::update(WiFiClient&, const String&, const String&)'

  128 |     t_httpUpdate_return update(WiFiClient& client, const String& url, const String& currentVersion = "");

      |                         ^~~~~~

C:\Users\Michael Zielinski\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:128:25: note:   candidate expects 3 arguments, 1 provided

In file included from D:\PC\Hardware\raspberry\fhem\epaper\ESPEInk_ESP8266\ESPEInk_ESP8266\ESPEInk_ESP8266.ino:19:

C:\Users\Michael Zielinski\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:142:25: note: candidate: 't_httpUpdate_return ESP8266HTTPUpdate::update(WiFiClient&, const String&, uint16_t, const String&, const String&)'

  142 |     t_httpUpdate_return update(WiFiClient& client, const String& host, uint16_t port, const String& uri = "/",

      |                         ^~~~~~

C:\Users\Michael Zielinski\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:142:25: note:   candidate expects 5 arguments, 1 provided

exit status 1

no matching function for call to 'ESP8266HTTPUpdate::update(String&)'

**Comment by Yattien** [comment]
Das Problem tritt mit den aktuellen ESP8266-Boarddefinitionen in Version ab 3.0.0. auf. Dort wurden einige APIs geändert, andere sind sogar ganz entfallen. Der master wurde auf die aktuellen Boarddefs angepasst, das Kompilieren sollte nun wieder funktionieren.
