### ISSUE TITLE
User Exception bei mqttclient.connect

### ISSUE THREAD

**Issue by maltejahn** [Yattien/ESPEInk_ESP8266#4]
Folgende Fehlermeldung erhalte ich:

> ESPEInk_ESP8266 v18, reset reason='Software/System restart'...
> Entering setup...
>  Reading config file...
>  Config file read.
>  Connecting to WiFi...
>  Connected to WiFi.
>  Using configuration:
>   MQTT Server: 192.168.0.243:1883, Client: ESPEInk_f4cfa26c8fe5
>   MQTT UpdateStatusTopic: stat/espeinkflur/needUpdate
>   MQTT CommandTopic: cmd/espeinkflur/upload
>   sleep time: 60
>   firmware base URL: 
>   MQTT Server config 989898944.
> Setup complete.
> Connecting to MQTT...
> 
> 
> User exception (panic/abort/assert)

Das ganze entsteht wohl hier:
> if (!mqttClient.connect(ctx.mqttClientName, NULL, NULL, NULL, 0, 0, NULL, 0)) {

ersetze ich die Funktion einfach durch if(1), so stürzt der Arme ESP8266 zumindest nicht ab. Zusätzlich habe ich Passwort/User des MQTT auf "NULL" gesetzt - der MQTT Server hat kein Passwort.

Mit einem Beispiel (Arduino -> PubSubClient -> mqtt_ESP8266) kommen Daten am Server an. Von daher sollte der Server/mosquitto in Ordnung sein.

Stehe jetzt auf dem Schlauch wie ich das weiter debuggen könnte.

Welche Bibliotheksversionen werden verwendet?
Bibliothek WiFiManager in Version 2.0.3-alpha 
Bibliothek ESP8266WiFi in Version 1.0 
Bibliothek ESP8266WebServer in Version 1.0
Bibliothek DNSServer in Version 1.1.1
Bibliothek ESP8266HTTPClient in Version 1.2
Bibliothek ESP8266httpUpdate in Version 1.3
Bibliothek ArduinoJson in Version 6.18.0 
Bibliothek PubSubClient in Version 2.7 Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\SPI  wird verwendet

Verwendet wird ein Waveshare e-paper ESP8266 Driver Board

Grüße
Malte

Btw: Ist das nicht ein bisschen kurz? char mqttClientName[21];

**Comment by Yattien** [comment]
Danke für die Meldung. Die Exception entstand im master und sollte mit dem aktuellen HEAD nicht mehr auftreten

> Btw: Ist das nicht ein bisschen kurz? char mqttClientName[21];

Der Clientname wird aus dem String "ESPEInk_" (8 Zeichen), der Mac-Adresse (12 Zeichen) + abschließende 0 gebildet. Sollte so passen.
